version: "3"

networks: 
    laracasts-videogames:

services: 
    apache:
        build: 
            context: ""
            dockerfile: ./docker/Dockerfile
        container_name: apache
        depends_on: 
            - mysql
        ports: 
            - 8080:80
        volumes: 
            - .:/var/www/html:cached
        networks:
            - laracasts-videogames
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "23306:3306"
        volumes:
            - ./mysql:/var/lib/mysql:cached
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laracasts-videogames